SELECT A.CART_ID,IF(A.MINIMUM_REQUIREMENT< A.PRICE , "0", "1") AS ABUSED
FROM (SELECT C.CART_ID, C.MINIMUM_REQUIREMENT, P.PRICE
FROM COUPONS C, (
    SELECT CART_ID,SUM(PRICE) PRICE FROM CART_PRODUCTS GROUP BY CART_ID) P
WHERE C.CART_ID = P.CART_ID) A
ORDER BY A.CART_ID
